version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpseclib/phpseclib
    versions:
    - 3.0.7
  - dependency-name: doctrine/dbal
    versions:
    - 2.12.1
    - 2.13.0
  - dependency-name: symfony/http-kernel
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: facade/ignition
    versions:
    - 1.16.16
  - dependency-name: laravel/tinker
    versions:
    - 2.6.0
  - dependency-name: laravel/framework
    versions:
    - 6.20.12
  - dependency-name: mockery/mockery
    versions:
    - 1.4.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: swiper
    versions:
    - 6.4.10
    - 6.4.11
    - 6.4.12
    - 6.4.14
    - 6.4.15
    - 6.4.9
    - 6.5.0
    - 6.5.5
    - 6.5.6
    - 6.5.7
  - dependency-name: lodash
    versions:
    - 4.17.20
