language: php

php:
  - 7.2
  - 7.3

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - rm composer.lock
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit
