language: php

php:
  - 7.2
  - 7.3

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

before_script:
  - cp .env.travis .env
  - rm composer.lock
  - composer self-update
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - npm install
  - npm run prod

script:
  - vendor/bin/phpunit
